language: python
sudo: false

python:
  - 3.7

env:
  - PANDAS_VERSION=1.0.1

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # required for using mkl-service
  - export MKL_THREADING_LAYER=GNU
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - cp pyfolio/tests/matplotlibrc .

install:
  - conda create -q -n testenv --yes python=$TRAVIS_PYTHON_VERSION ipython numpy scipy nose matplotlib pandas=$PANDAS_VERSION flake8 seaborn scikit-learn runipy pandas-datareader
  - source activate testenv
  - pip install -e .[all]

script:
  - nosetests $TESTCMD

notifications:
  email: true
